export const AUDIT_ACTIONS = {
  AUTH_LOGIN: 'auth.login',
  AUTH_REFRESH: 'auth.refresh',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_PASSWORD_RESET_REQUEST: 'auth.password_reset.request',
  AUTH_PASSWORD_RESET_CONFIRM: 'auth.password_reset.confirm',
  AUTH_CHANGE_PASSWORD: 'auth.change_password',
  USER_UPDATE: 'user.update',
  USER_ROLE_CHANGE: 'user.role.change',
  USER_STATUS_CHANGE: 'user.status.change',
  SCHEDULE_CREATE: 'schedule.create',
  SCHEDULE_UPDATE: 'schedule.update',
  SCHEDULE_CANCEL: 'schedule.cancel',
  SCHEDULE_RESCHEDULE: 'schedule.reschedule',
  SCHEDULE_SUBSTITUTE: 'schedule.substitute',
  SCHEDULE_BULK_CREATE: 'schedule.bulk.create',
  SCHEDULE_BULK_CANCEL: 'schedule.bulk.cancel',
  SCHEDULE_TEMPLATE_CREATE: 'schedule.template.create',
  SCHEDULE_TEMPLATE_UPDATE: 'schedule.template.update',
  SCHEDULE_TEMPLATE_DELETE: 'schedule.template.delete',
  SCHEDULE_TEMPLATE_APPLY: 'schedule.template.apply',
  SCHEDULE_DELETE: 'schedule.delete',
  GRADE_CREATE: 'grade.create',
  GRADE_UPDATE: 'grade.update',
  GRADE_SUBMISSION: 'grade.submission.grade',
  SURVEY_PUBLISH: 'survey.publish',
  SURVEY_CLOSE: 'survey.close',
  FILE_UPLOAD: 'file.upload',
  FILE_DELETE: 'file.delete',
  ELECTIVE_PERIOD_PUBLISH: 'elective.period.publish',
  ELECTIVE_PERIOD_CLOSE: 'elective.period.close',
  ELECTIVE_PERIOD_STATUS_CHANGE: 'elective.period.status.change',
  ELECTIVE_PERIOD_FINALIZE: 'elective.period.finalize',
  ELECTIVE_SELECTION_SELECT: 'elective.selection.select',
  ELECTIVE_SELECTION_CANCEL: 'elective.selection.cancel',
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',
  AUDIT_LOG_VIEW: 'audit.view',
  AUDIT_LOG_EXPORT: 'audit.export',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
