export const AUDIT_ACTIONS = {
  AUTH_LOGIN: 'auth.login',
  AUTH_REFRESH: 'auth.refresh',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_PASSWORD_RESET_REQUEST: 'auth.password_reset.request',
  AUTH_PASSWORD_RESET_CONFIRM: 'auth.password_reset.confirm',
  AUTH_CHANGE_PASSWORD: 'auth.change_password',
  USER_UPDATE: 'user.update',
  USER_ROLE_CHANGE: 'user.role.change',
  USER_STATUS_CHANGE: 'user.status.change',
  COURSE_CREATE: 'course.created',
  COURSE_UPDATE: 'course.updated',
  COURSE_ARCHIVE: 'course.archived',
  COURSE_RESTORE: 'course.restored',
  COURSE_MOODLE_URL_CHANGE: 'course.moodle_url.changed',
  COURSE_ASSIGNMENT_RESOURCES_UPDATE: 'course_assignment.resources.updated',
  SCHEDULE_ONLINE_LINK_SET: 'schedule.online_link.set',
  SCHEDULE_ONLINE_LINK_DELETED: 'schedule.online_link.deleted',
  SCHEDULE_SNAPSHOT_REFRESH: 'schedule.snapshot.refresh',
  SURVEY_PUBLISH: 'survey.publish',
  SURVEY_UNPUBLISH: 'survey.unpublish',
  SURVEY_ACTIVATE: 'survey.activate',
  SURVEY_CLOSE: 'survey.close',
  FILE_UPLOAD: 'file.upload',
  FILE_DELETE: 'file.delete',
  ELECTIVE_PERIOD_PUBLISH: 'elective.period.publish',
  ELECTIVE_PERIOD_CLOSE: 'elective.period.close',
  ELECTIVE_PERIOD_STATUS_CHANGE: 'elective.period.status.change',
  ELECTIVE_DISCIPLINE_STATUS_CHANGE: 'elective.discipline.status.change',
  ELECTIVE_PERIOD_FINALIZE: 'elective.period.finalize',
  ELECTIVE_SELECTION_SELECT: 'elective.selection.select',
  ELECTIVE_SELECTION_CANCEL: 'elective.selection.cancel',
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',
  AUDIT_LOG_VIEW: 'audit.view',
  AUDIT_LOG_EXPORT: 'audit.export',
  ACADEMIC_TERM_ACTIVATE: 'academic_term.activate',
  STUDENT_PROFILE_SYNC: 'student_profile.sync',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
